### ISSUE TITLE
Error: The module 'sharp.node' was compiled against a different Node.js

### ISSUE THREAD

**Issue by LeGiangAnh** [pixelnest/presskit.html#14]
Please help.
```
E:\Google Drive\Imba\Marketing\Web\presskit.html-master\data>presskit build
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '\\?\C:\Users\USER\AppData\Roaming\npm\node_modules\presskit\node_modules\sharp\build\Release\sharp.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\USER\AppData\Roaming\npm\node_modules\presskit\node_modules\sharp\lib\constructor.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```

**Comment by zvinless** [comment]
The sharp dependency version needs to be updated to support Node 12. Until then, you'll need to use Node <= 11

**Comment by LeGiangAnh** [comment]
Im using node 10

**Comment by solarsailer** [comment]
The dependencies have been updated. Give it a try. ;)
